name: Build and Test this PR

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'README*'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'README*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17

    - name: Get Date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y-%m")"
      shell: bash
    - name: Cache Maven Repository
      id: cache-maven
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        # refresh cache every month to avoid unlimited growth
        key: maven-repo-${{ steps.get-date.outputs.date }}

    - name: Build with Maven
      run: mvn -B formatter:validate clean install -DskipTests -DskipITs --file pom.xml

    - name: Find and store Maven home
      id: maven-home-discovery
      run: echo "detected-mvn-home=$(mvn -v | grep 'Maven home:' | sed -e 's|Maven home:| |' | xargs)" >> "$GITHUB_OUTPUT"

    - name: Run tests
      run: mvn clean verify
      env:
        MAVEN_HOME: ${{ steps.maven-home-discovery.outputs.detected-mvn-home }}

    - name: Delete Artifacts From Cache
      shell: bash
      run: rm -rf ~/.m2/repository/io/quarkus/bot/
